# syntax=docker/dockerfile:1

FROM node:lts-alpine3.17

#Create app directory
WORKDIR /usr/src/app

#Install app dependencies
COPY package*.json ./

RUN npm install
#if you are building your code for production
# RUN npm ci --only=production

# Bundle app source

COPY . .

EXPOSE 8080
CMD ["node", "server.js"]
